<a href="https://colab.research.google.com/github/lacteavian/miuul_machine_learning_bootcamp/blob/main/week2_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [4]:
a*b

array([ 2,  6, 12, 20])

In [8]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.random.randint(0,10, size=10)

array([4, 9, 3, 6, 8, 1, 6, 4, 1, 3])

In [13]:
np.random.normal(10, 4, (3,4))

array([[10.50671904, 12.99349481, 10.48743641,  8.07156235],
       [ 4.8528779 , 13.60375339, 12.48388604, 13.11397439],
       [ 8.7821303 ,  7.13467686,  3.15022261,  6.2042864 ]])

numpy features

In [19]:
a=np.random.randint(1, 10, (2,4))

In [20]:
a.ndim

2

In [21]:
a.shape

(2, 4)

In [22]:
a.dtype

dtype('int64')

In [23]:
a.size

8

reshaping

In [24]:
b = np.random.randint(1,10, size=9)

In [26]:
b

array([1, 4, 5, 1, 1, 1, 3, 9, 5])

In [27]:
b.reshape(3,3)

array([[1, 4, 5],
       [1, 1, 1],
       [3, 9, 5]])

index operations

In [30]:
c = np.random.randint(10, size=10)
c

array([3, 6, 8, 6, 5, 6, 8, 0, 4, 5])

In [31]:
c[0]

3

In [32]:
c[0:5]

array([3, 6, 8, 6, 5])

In [33]:
c[0] = 12
c

array([12,  6,  8,  6,  5,  6,  8,  0,  4,  5])

In [36]:
m = np.random.randint(10 , size=(3,5))
m

array([[2, 2, 5, 0, 7],
       [0, 7, 2, 1, 5],
       [3, 7, 5, 9, 1]])

In [37]:
m[0,0]

2

In [38]:
m[2,3] = 17
m

array([[ 2,  2,  5,  0,  7],
       [ 0,  7,  2,  1,  5],
       [ 3,  7,  5, 17,  1]])

In [40]:
m[2,3] = 99.9
m

array([[ 2,  2,  5,  0,  7],
       [ 0,  7,  2,  1,  5],
       [ 3,  7,  5, 99,  1]])

In [41]:
m[:, 0]

array([2, 0, 3])

In [42]:
m[1, :]

array([0, 7, 2, 1, 5])

In [43]:
m[0:2, 0:3]

array([[2, 2, 5],
       [0, 7, 2]])

fancy index

In [47]:
v = np.arange(0,10, 2)
v

array([0, 2, 4, 6, 8])

In [48]:
catch=[1,2,3]

In [49]:
v[catch]

array([2, 4, 6])

numpy conditions

In [50]:
v = np.array([1,2,3,4,5])

In [51]:
v < 3

array([ True,  True, False, False, False])

In [52]:
v[v<3]

array([1, 2])

mathematical operations

In [54]:
v = np.array([1,2,3,4,5])

In [56]:
v / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [57]:
v * 3 / 4

array([0.75, 1.5 , 2.25, 3.  , 3.75])

In [58]:
v ** 2

array([ 1,  4,  9, 16, 25])

In [59]:
v - 3

array([-2, -1,  0,  1,  2])

In [61]:
np.subtract(v,3)


array([-2, -1,  0,  1,  2])

In [62]:
np.add(v,1)


array([2, 3, 4, 5, 6])

In [63]:
np.mean(v)


3.0

In [64]:
np.sum(v)


15

In [65]:
np.min(v)


1

In [66]:
np.max(v)


5

In [67]:
np.var(v)

2.0

5x_0 + x_1 = 12

x_0 + 3x_1 = 10

In [70]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

In [71]:
np.linalg.solve(a, b)

array([1.85714286, 2.71428571])

# PANDAS

In [72]:
import pandas as pd

In [74]:
s = pd.Series([10,77,12,4,5])

In [75]:
type(s)

pandas.core.series.Series

In [76]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [80]:
s.dtype

dtype('int64')

In [77]:
s.size

5

In [78]:
s.ndim

1

In [79]:
s.values

array([10, 77, 12,  4,  5])

In [81]:
type(s.values)

numpy.ndarray

In [83]:
s.head(3)

0    10
1    77
2    12
dtype: int64

In [84]:
s.tail(3)

2    12
3     4
4     5
dtype: int64

reading data

In [86]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

In [87]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0

quick look at data

In [151]:
import seaborn as sns

In [209]:
df = sns.load_dataset("titanic")

In [210]:
type(df)

pandas.core.frame.DataFrame

In [211]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [212]:
df.shape

(891, 15)

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [214]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [215]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [216]:
df.isnull().values.any()

True

In [217]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [218]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [219]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

selection in pandas

In [220]:
df[0:13]

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
1          1       1  female  38.0      1      0  71.2833        C   First   
2          1       3  female  26.0      0      0   7.9250        S   Third   
3          1       1  female  35.0      1      0  53.1000        S   First   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
6          0       1    male  54.0      0      0  51.8625        S   First   
7          0       3    male   2.0      3      1  21.0750        S   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500        S   First   
12         0       3    male  20.0      0      0   8.0500        S   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
1   woman       False    C    Cherbourg   yes  False  
2   woman       False  NaN  Southampton   yes   True  
3   woman       False    C  Southampton   yes  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
7   child       False  NaN  Southampton    no  False  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
12    man        True  NaN  Southampton    no   True

In [221]:
df.drop(0,axis=0).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [222]:
delete_indexes = [1,2,3,6,7]

In [223]:
df.drop(delete_indexes,axis=0).head(8)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0          0       3    male  22.0      1      0   7.2500        S   Third   
4          0       3    male  35.0      0      0   8.0500        S   Third   
5          0       3    male   NaN      0      0   8.4583        Q   Third   
8          1       3  female  27.0      0      2  11.1333        S   Third   
9          1       2  female  14.0      1      0  30.0708        C  Second   
10         1       3  female   4.0      1      1  16.7000        S   Third   
11         1       1  female  58.0      0      0  26.5500        S   First   
12         0       3    male  20.0      0      0   8.0500        S   Third   

      who  adult_male deck  embark_town alive  alone  
0     man        True  NaN  Southampton    no  False  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
8   woman       False  NaN  Southampton   yes  False  
9   child       False  NaN    Cherbourg   yes  False  
10  child       False    G  Southampton   yes  False  
11  woman       False    C  Southampton   yes   True  
12    man        True  NaN  Southampton    no   True

In [189]:
# df.drop(delete_indexes, axis=0,inplace=True)

In [224]:
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [225]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [226]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [227]:
df.index=df["age"]
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
age                                                                           
22.0         0       3    male  22.0      1      0   7.2500        S  Third   
38.0         1       1  female  38.0      1      0  71.2833        C  First   
26.0         1       3  female  26.0      0      0   7.9250        S  Third   
35.0         1       1  female  35.0      1      0  53.1000        S  First   
35.0         0       3    male  35.0      0      0   8.0500        S  Third   

        who  adult_male deck  embark_town alive  alone  
age                                                     
22.0    man        True  NaN  Southampton    no  False  
38.0  woman       False    C    Cherbourg   yes  False  
26.0  woman       False  NaN  Southampton   yes   True  
35.0  woman       False    C  Southampton   yes  False  
35.0    man        True  NaN  Southampton    no   True

In [228]:
df.drop("age", axis=1, inplace=True)


In [229]:
df["age"] = df.index

In [230]:
df.head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1       1  female      1      0  71.2833        C  First  woman   
26.0         1       3  female      0      0   7.9250        S  Third  woman   
35.0         1       1  female      1      0  53.1000        S  First  woman   
35.0         0       3    male      0      0   8.0500        S  Third    man   

      adult_male deck  embark_town alive  alone   age  
age                                                    
22.0        True  NaN  Southampton    no  False  22.0  
38.0       False    C    Cherbourg   yes  False  38.0  
26.0       False  NaN  Southampton   yes   True  26.0  
35.0       False    C  Southampton   yes  False  35.0  
35.0        True  NaN  Southampton    no   True  35.0

In [231]:
df.drop("age", axis=1, inplace=True)


In [232]:
df.head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1       1  female      1      0  71.2833        C  First  woman   
26.0         1       3  female      0      0   7.9250        S  Third  woman   
35.0         1       1  female      1      0  53.1000        S  First  woman   
35.0         0       3    male      0      0   8.0500        S  Third    man   

      adult_male deck  embark_town alive  alone  
age                                              
22.0        True  NaN  Southampton    no  False  
38.0       False    C    Cherbourg   yes  False  
26.0       False  NaN  Southampton   yes   True  
35.0       False    C  Southampton   yes  False  
35.0        True  NaN  Southampton    no   True

In [233]:
df = df.reset_index()

In [234]:
df.head()

age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third   
1  38.0         1       1  female      1      0  71.2833        C  First   
2  26.0         1       3  female      0      0   7.9250        S  Third   
3  35.0         1       1  female      1      0  53.1000        S  First   
4  35.0         0       3    male      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [237]:
df = sns.load_dataset("titanic")

In [238]:
pd.set_option("display.max_columns",None)

In [239]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [240]:
"age" in df

True

In [241]:
type(df["age"])

pandas.core.series.Series

In [242]:
type(df[["age"]])

pandas.core.frame.DataFrame

In [243]:
df[["age"]].head()

age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [245]:
df[["age","alive"]].head()

age alive
0  22.0    no
1  38.0   yes
2  26.0   yes
3  35.0   yes
4  35.0    no

In [246]:
col_names = ["age","adult_male","alive"]

In [248]:
df[col_names].head()

age  adult_male alive
0  22.0        True    no
1  38.0       False   yes
2  26.0       False   yes
3  35.0       False   yes
4  35.0        True    no

In [250]:
df.loc[:, df.columns.str.contains("age")].head()

age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [251]:
df.loc[:, ~df.columns.str.contains("age")].head()

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   
3         1       1  female      1      0  53.1000        S  First  woman   
4         0       3    male      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [252]:
df.iloc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

In [255]:
df.loc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False

In [253]:
df.iloc[0,0]

0

In [254]:
df.iloc[0:4,0:3]

survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female

In [257]:
df.loc[0:3, "age"] # you cant use iloc with labels

0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64

In [258]:
df.loc[0:3, col_names]

age  adult_male alive
0  22.0        True    no
1  38.0       False   yes
2  26.0       False   yes
3  35.0       False   yes

In [260]:
df[df["age"] > 50].head()

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
6          0       1    male  54.0      0      0  51.8625        S   First   
11         1       1  female  58.0      0      0  26.5500        S   First   
15         1       2  female  55.0      0      0  16.0000        S  Second   
33         0       2    male  66.0      0      0  10.5000        S  Second   
54         0       1    male  65.0      0      1  61.9792        C   First   

      who  adult_male deck  embark_town alive  alone  
6     man        True    E  Southampton    no   True  
11  woman       False    C  Southampton   yes   True  
15  woman       False  NaN  Southampton   yes   True  
33    man        True  NaN  Southampton    no   True  
54    man        True    B    Cherbourg    no  False

In [262]:
df[df["age"] > 50]["age"].count()

64

In [265]:
df.loc[df["age"] > 50, ["age","class"]].head()

age   class
6   54.0   First
11  58.0   First
15  55.0  Second
33  66.0  Second
54  65.0   First

In [274]:
df.loc[(df["age"] > 50)
& (df["sex"] == "male")
& ((df["embark_town"] == "Cherbourg") | (df["embark_town"] == "Southampton")),
  ["age","class","embark_town"]].head()

age   class  embark_town
6   54.0   First  Southampton
33  66.0  Second  Southampton
54  65.0   First    Cherbourg
94  59.0   Third  Southampton
96  71.0   First    Cherbourg

aggregation & grouping

In [275]:
df["age"].mean()

29.69911764705882

In [276]:
df.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [278]:
type(df.groupby("sex")["age"].mean())

pandas.core.series.Series

In [277]:
df.groupby("sex").agg({"age": "mean"})

age
sex              
female  27.915709
male    30.726645

In [279]:
type(df.groupby("sex").agg({"age": "mean"}))

pandas.core.frame.DataFrame

In [280]:
df.groupby("sex").agg({"age": ["mean","sum"]})

age          
             mean       sum
sex                        
female  27.915709   7286.00
male    30.726645  13919.17

In [282]:
df.groupby("sex").agg({"age": ["mean","sum"],
                       "survived": "mean"})

age            survived
             mean       sum      mean
sex                                  
female  27.915709   7286.00  0.742038
male    30.726645  13919.17  0.188908

In [288]:
df.groupby(["sex","embark_town","class"]).agg({
    "age": "mean",
    "survived": "mean",
    "sex": "count"})

age  survived  sex
sex    embark_town class                           
female Cherbourg   First   36.052632  0.976744   43
                   Second  19.142857  1.000000    7
                   Third   14.062500  0.652174   23
       Queenstown  First   33.000000  1.000000    1
                   Second  30.000000  1.000000    2
                   Third   22.850000  0.727273   33
       Southampton First   32.704545  0.958333   48
                   Second  29.719697  0.910448   67
                   Third   23.223684  0.375000   88
male   Cherbourg   First   40.111111  0.404762   42
                   Second  25.937500  0.200000   10
                   Third   25.016800  0.232558   43
       Queenstown  First   44.000000  0.000000    1
                   Second  57.000000  0.000000    1
                   Third   28.142857  0.076923   39
       Southampton First   41.897188  0.354430   79
                   Second  30.875889  0.154639   97
                   Third   26.574766  0.128302  265

pivot table

In [289]:
df.pivot_table("survived","sex","embarked")

embarked         C         Q         S
sex                                   
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [290]:
df.pivot_table("survived","sex","embarked", aggfunc="std")

embarked         C         Q         S
sex                                   
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [291]:
df.pivot_table("survived", "sex",["embarked", "class"])

embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First   
sex                                                                    
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333   
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430   

embarked                      
class       Second     Third  
sex                           
female    0.910448  0.375000  
male      0.154639  0.128302

In [292]:
df["new_age"] = pd.cut(df["age"], [0, 10, 18, 25, 40, 90])

In [295]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone   new_age  
0    man        True  NaN  Southampton    no  False  (18, 25]  
1  woman       False    C    Cherbourg   yes  False  (25, 40]  
2  woman       False  NaN  Southampton   yes   True  (25, 40]  
3  woman       False    C  Southampton   yes  False  (25, 40]  
4    man        True  NaN  Southampton    no   True  (25, 40]

In [296]:
df.pivot_table("survived", "sex", "new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
sex                                                      
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

In [297]:
df.pivot_table("survived", "sex", ["new_age", "class"])

new_age (0, 10]                   (10, 18]                   (18, 25]  \
class     First Second     Third     First Second     Third     First   
sex                                                                     
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176   
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333   

new_age                      (25, 40]                      (40, 90]            \
class      Second     Third     First    Second     Third     First    Second   
sex                                                                             
female   0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154   
male     0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238   

new_age            
class       Third  
sex                
female   0.111111  
male     0.064516